### ISSUE TITLE
Issues migrating existing install to docker

### ISSUE THREAD

**Issue by tomuta** [owncloud-docker/base#132]
I'm trying to migrate an existing install which was running directly on a Debian Stretch system to a dockerized install. However, I'm running into issues I haven't been able to figure out. Here's my `docker-compose.yml`:

```yml
version: '3.1'

services:
  owncloud:
    image: owncloud/server:latest
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /home/owncloud_data:/mnt/data
    environment:
# not setting OWNCLOUD_VOLUME_FILES causes the `datadirectory` setting to incorrectly point to /mnt/data/files
      - OWNCLOUD_VOLUME_FILES=/mnt/data
      - OWNCLOUD_VERSION=latest
      - OWNCLOUD_DOMAIN=xxxxxxxxxxx
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_DB_HOST=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=xxxxxxxxxxx
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=xxxxxxxxxxx
      - OWNCLOUD_SECRET=xxxxxxxxxxx
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxxxxx
    volumes:
      - ./db:/var/lib/mysql
```

The existing install used a mysql database, which I successfully backed up and restored into the mysql image. I verified that that database in the mysql container contains the same tables and users as the existing install I'm migrating from. I also verified that the owncloud container can connect and authenticate to the cloned database with these credentials.

However, the owncloud container keeps failing like this:
```
owncloud_1  | Creating volume folders...
owncloud_1  | Creating hook folders...
owncloud_1  | Waiting for MySQL...
owncloud_1  | services are ready!
owncloud_1  | Removing custom folder...
owncloud_1  | Linking custom folder...
owncloud_1  | Removing config folder...
owncloud_1  | Linking config folder...
owncloud_1  | Writing config file...
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Fixing hook perms...
owncloud_1  | Installing server database...
owncloud_1  | The username is already being used
```

It seems like it's trying to create a fresh database even though it's already there? How can I stop it from doing it and just use the existing installation?

The other issue I can't quite figure out is why the value for `secret` in `config.php` changes every time the container restarts due to the failure above, even though `env` inside the owncloud container shows the correct value for `OWNCLOUD_SECRET`, and it seems that `overwrite.config.php` should have replaced it unconditionally.

Another oddity that I noticed that I had to set `OWNCLOUD_VOLUME_FILES`, otherwise `datadirectory` in `config.php` had `/files` appended to it. Is this a bug?
