### ISSUE TITLE
Apache proxy don't allow the correct URL 

### ISSUE THREAD

**Issue by matthias1403** [owncloud-docker/base#210]
Hello,

I have migrated my local owncloud installation to a docker environment. Everything runs smooth except the proxy, which I need for securing the connection with letsencrypt.
The owncloud needs to run at a subpath "/owncloud" in my environment to keep all the clients working.

Apache settings:
```
        <Location /owncloud>
                ProxyPass http://localhost:8080/owncloud
                ProxyPassReverse http://localhost:8080/owncloud
       </Location>
```
Docker-compose:
```

version: "3"

volumes:
  redis:
    driver: local
  mysql:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - OWNCLOUD_SUB_URL=/owncloud
```
 This leads to this message:

![image](https://user-images.githubusercontent.com/59503628/172791544-2b7957d6-387b-452c-857f-86eb1cb559b9.png)

If I remove the /owncloud subpath in my apache config, the proxy works in general, but it changes the URL to /owncloud/owncloud, which looks not nice and all my clients won't work with that.

Any ideas how to configure an apache2 proxy/docker owncloud correctly?

Thanks & Br, Matthias
