### ISSUE TITLE
Running behind a proxy on a sub-path

### ISSUE THREAD

**Issue by mebibou** [owncloud-docker/base#38]
I want to run owncloud using reverse proxy and nginx.
I set `OWNCLOUD_DOMAIN=mydomain.com` in the `.env` file.
I have the following `docker-compose.yml`:
```
version: '2.1'

volumes:
  owncloud:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    expose:
      - ${HTTP_PORT}
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_HOST=${OWNCLOUD_DB_HOST}
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=false
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - owncloud:/mnt/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - owncloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
```
and the following nginx.conf:
```
events {
	worker_connections 1024;
}

http {
  server_names_hash_bucket_size 512;

  server {
    listen 80;

    server_name _;

    location /owncloud/ {
      proxy_pass  http://owncloud/;
      rewrite     ^/owncloud(/.*) $1 break;
    }
  }
}
```
After `docker-compose up` I can go to `http://mydomain.com/owncloud` and the login page will appear, but all the resources will return a 500 error since it is trying to load them through the default location `/` which is not mapped to owncloud.
I tried to use `OWNCLOUD_SUB_URL=/ownloud/` but this will just redirect `http://mydomain.com/owncloud` to `http://mydomain.com/owncloud/owncloud` and is not going to fix the problem. I have other websites mapped in my nginx.conf that I didn't post here, which is why I use it like this. What's the correct way to map owncloud to a path using nginx as reverse proxy?
